

GET http://localhost:8000/api/users
apikey: xnyj7eOZpDvttQTK8wPk1oZkWxEfqd26

####

GET http://localhost:8000/api/users?fields=id,name&limit=1&skip=0
apikey: xnyj7eOZpDvttQTK8wPk1oZkWxEfqd26

###
PUT  http://localhost:8000/api/users/admin
Content-Type: application/json
apikey: xnyj7eOZpDvttQTK8wPk1oZkWxEfqd26

{"name":"admin"}

###
PATCH http://localhost:8000/api/users/admin
Content-Type: application/json
apikey: xnyj7eOZpDvttQTK8wPk1oZkWxEfqd26

{"name":"administrador del sistema"}

####

GET http://localhost:8000/api/users/admin
apikey: xnyj7eOZpDvttQTK8wPk1oZkWxEfqd26

###

PUT http://localhost:8000/api/users/admin/posts
Content-Type: application/x-www-form-urlencoded

title="First Post"&body="Lorem ipsum"
